#!/bin/sh
#
# Run tests for continuous integration.
#
# This script is normally run in a test container or VM, such as via GitHub
# Actions.
#
# Copyright 2015-2020 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

set -eux

# Normally, COMPILER is set based on the CI matrix, but provide a default in
# case someone runs this test by hand.
COMPILER="${COMPILER:-gcc}"

# Build everything.  Only use warnings when not building with C++, since the
# probe for warning flags currently doesn't work properly for g++.
./bootstrap
./configure CC="$COMPILER"
if [ "$COMPILER" = 'g++' ]; then
    make
else
    make warnings
fi

# Run the regular tests with valgrind for one of the builds.  Arbitrarily pick
# the GCC build.  (The assumption here is that other compilers won't produce
# sufficiently different code as to create memory management problems.)
if [ "$COMPILER" = 'gcc' ]; then
    make check-valgrind
else
    make check
fi

# Run some additional checks for one of the builds.  Arbitrarily pick the GCC
# build.
if [ "$COMPILER" = 'gcc' ]; then
    make check-cppcheck
fi
