#! /bin/sh
#
# Test of the libtap.sh bail function
#
# Copyright 2009, 2016 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

# Load the test library.
. "$C_TAP_SOURCE/tap/libtap.sh"

plan 2
ok "" true
bail Some error message
ok "" true
exit 0
