#! /bin/sh
#
# Test of the libtap.sh diag function.
#
# Copyright 2010, 2016 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

# Load the test library.
. "$C_TAP_SOURCE/tap/libtap.sh"

plan 1
diag 'foo'
ok 'first test' true
diag 'bar baz foo'
exit 0
