#!/bin/sh
#
# Test of the test_file_path utility function in libtap.sh.
#
# Copyright 2010, 2012, 2016 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

. "${C_TAP_SOURCE}/tap/libtap.sh"

echo "Path to c-file: ${C_TAP_BUILD}/libtap/basic/c-file" > sh-file.output
echo "Path to c-basic.output: ${C_TAP_SOURCE}/libtap/basic/c-basic.output" \
    >> sh-file.output
echo "Path to c-file: " >> sh-file.output
echo "Path to c-basic.output: " >> sh-file.output
path=`test_file_path 'libtap/basic/c-file'`
echo "Path to c-file: $path"
path=`test_file_path 'libtap/basic/c-basic.output'`
echo "Path to c-basic.output: $path"
C_TAP_BUILD=
C_TAP_SOURCE=
path=`test_file_path 'libtap/basic/c-file'`
echo "Path to c-file: $path"
path=`test_file_path 'libtap/basic/c-basic.output'`
echo "Path to c-basic.output: $path"
exit 0
