#! /bin/sh
#
# Test of the libtap.sh end summary with all successful tests and a plan of 1.
#
# Copyright 2009, 2016 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

# Load the test library.
. "$C_TAP_SOURCE/tap/libtap.sh"

plan 1
ok "first" true
exit 0
