#!/bin/sh
echo 1..3
if [ "$1" = "--opt" ];         then echo ok 1; else echo not ok 1; fi
if [ "$2" = "--another-opt" ]; then echo ok 2; else echo not ok 2; fi
if echo "$3" | grep '/harness/options/executable\.t$' >/dev/null; then
    echo ok 3
else
    echo not ok 3
fi
