#ifndef CONFIG_H
#define CONFIG_H

/*
   Name : MARPA_LIB_VERSION
   Usage: Version of @PROJECT_NAME@
*/
#define MARPA_LIB_VERSION "@MARPA_LIB_VERSION@"
#define MARPA_LIB_MAJOR_VERSION @MARPA_LIB_MAJOR_VERSION@
#define MARPA_LIB_MINOR_VERSION @MARPA_LIB_MINOR_VERSION@
#define MARPA_LIB_MICRO_VERSION @MARPA_LIB_PATCH_VERSION@
#define HAVE_STDINT_H @HAVE_STDINT_H@
#define HAVE_INTTYPES_H @HAVE_INTTYPES_H@

#endif /* CONFIG_H */
